{% set version = "2.0.2" %}

package:
  name: async-lru
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/async_lru/async-lru-{{ version }}.tar.gz
  sha256: 3b87ec4f2460c52cc7916a0138cc606b584c75d1ef7d661853c95d1d3acb869a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - typing_extensions >=4.0.0

test:
  source_files:
    - tests
  imports:
    - async_lru
  commands:
    - pip check
    - mypy -m async_lru
    - pytest -vv --cov=async_lru --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=100
  requires:
    - mypy
    - pip
    - pytest-asyncio
    - pytest-cov

about:
  home: https://github.com/aio-libs/async-lru
  summary: Simple lru_cache for asyncio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
