{% set name = "async-lru" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 481d52ccdd27275f42c43a928b4a50c3bfb2d67af4e78b170e3e0bb39c66e5bb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - typing_extensions >=4.0.0  # [py<311]

test:
  source_files:
    - tests
  imports:
    - async_lru
  commands:
    - pip check
    - pytest -vv --asyncio-mode=auto --cov=async_lru --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=89
  requires:
    - pip
    - pytest-asyncio
    - pytest-cov
    - pytest-timeout

about:
  home: https://github.com/aio-libs/async-lru
  summary: Simple lru_cache for asyncio
  description: Simple lru_cache for asyncio
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/aio-libs/async-lru
  dev_url: https://github.com/aio-libs/async-lru

extra:
  recipe-maintainers:
    - bollwyvl
