{% set version = "2.0.1" %}

package:
  name: async-lru
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/async_lru/async-lru-{{ version }}.tar.gz
  sha256: 2bba4fe007a7da40a8da0388a370e2beae2f602edef12b2e705ae4c781d0fc31

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - typing_extensions >=4.0.0

test:
  imports:
    - async_lru
  commands:
    - pip check
    - mypy -m async_lru
  requires:
    - pip
    - mypy

about:
  home: https://github.com/aio-libs/async_lru
  summary: Simple lru_cache for asyncio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
