{% set name = "async_lru" %}
{% set version = "1.0.3" %}

package:
  name: {{ name.replace("_", "-") }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: c2cb9b2915eb14e6cf3e717154b40f715bf90e596d73623677affd0d1fbcd32a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - async_lru
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wikibusiness/async_lru
  summary: Simple lru_cache for asyncio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
