{% set version = "2.0.0" %}

package:
  name: async-lru
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/async_lru/async-lru-{{ version }}.tar.gz
  sha256: 40b0014602172e9a45b83f53591881490abd9b545c4f9fa94242a916ec7cd112

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - typing_extensions >=4.0.0

test:
  imports:
    - async_lru
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/async_lru
  summary: Simple lru_cache for asyncio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
